// Pins M12 Seefahrt T00 auf v8-Code: Auftrags- und Brandziehung vor E2/E3, Testwelt mit bekanntem d.
// Gemessen auf unverändertem v8-Code, Datum 2026-10-05.
export const SEE_SEEDS = [1, 3, 42] as const;
/** orderForPeriod(seed, k, 4) für k = 0 … 19, je Seed: [good, amount] (AK-E3-04). */
export const ORDER_PINS: Record<number, [string, number][]> = {
  1: [
    ['cloth', 7],
    ['cloth', 8],
    ['wool', 16],
    ['cloth', 8],
    ['cloth', 6],
    ['cloth', 9],
    ['wood', 40],
    ['stone', 10],
    ['cane', 11],
    ['glass', 7],
    ['food', 16],
    ['stone', 14],
    ['cane', 20],
    ['cane', 14],
    ['wood', 23],
    ['cloth', 6],
    ['stone', 17],
    ['cloth', 7],
    ['wool', 17],
    ['cloth', 7],
  ],
  3: [
    ['food', 17],
    ['wool', 19],
    ['stone', 16],
    ['stone', 11],
    ['rum', 7],
    ['cloth', 8],
    ['cloth', 7],
    ['glass', 7],
    ['food', 10],
    ['cloth', 7],
    ['stone', 16],
    ['wood', 32],
    ['cloth', 8],
    ['stone', 12],
    ['cloth', 9],
    ['wood', 36],
    ['food', 13],
    ['wool', 17],
    ['wood', 27],
    ['rum', 7],
  ],
  42: [
    ['stone', 11],
    ['cane', 17],
    ['wool', 14],
    ['cloth', 7],
    ['stone', 15],
    ['food', 17],
    ['stone', 12],
    ['cloth', 11],
    ['rum', 7],
    ['glass', 8],
    ['food', 20],
    ['food', 18],
    ['wool', 13],
    ['cane', 13],
    ['rum', 7],
    ['wool', 13],
    ['glass', 4],
    ['stone', 14],
    ['wood', 24],
    ['wood', 32],
  ],
};
/** Brand: rollCrisis(seed, k, 4, flammableRect(w)).tile für k = 0 … 29 in fireWorld(seed) (AK-E2-07). */
export const FIRE_PINS: Record<number, ({ x: number; y: number } | null)[]> = {
  1: [
    null,
    { x: 23, y: 19 },
    { x: 23, y: 19 },
    { x: 23, y: 19 },
    null,
    { x: 22, y: 18 },
    null,
    null,
    { x: 22, y: 19 },
    { x: 23, y: 18 },
    { x: 23, y: 19 },
    null,
    null,
    { x: 23, y: 18 },
    null,
    null,
    null,
    { x: 23, y: 19 },
    null,
    { x: 22, y: 19 },
    { x: 23, y: 19 },
    null,
    null,
    null,
    null,
    { x: 22, y: 19 },
    null,
    { x: 22, y: 18 },
    { x: 23, y: 19 },
    null,
  ],
  3: [
    null,
    { x: 36, y: 33 },
    null,
    null,
    { x: 36, y: 32 },
    { x: 36, y: 32 },
    { x: 36, y: 32 },
    null,
    null,
    null,
    { x: 35, y: 32 },
    null,
    { x: 36, y: 33 },
    { x: 36, y: 32 },
    null,
    { x: 35, y: 32 },
    null,
    null,
    null,
    { x: 36, y: 32 },
    null,
    { x: 35, y: 33 },
    { x: 35, y: 32 },
    null,
    null,
    null,
    { x: 35, y: 33 },
    null,
    { x: 35, y: 32 },
    null,
  ],
  42: [
    null,
    { x: 25, y: 43 },
    { x: 24, y: 43 },
    { x: 25, y: 42 },
    null,
    null,
    { x: 24, y: 42 },
    { x: 24, y: 42 },
    null,
    null,
    { x: 24, y: 42 },
    null,
    null,
    null,
    null,
    null,
    null,
    { x: 25, y: 43 },
    { x: 24, y: 43 },
    { x: 24, y: 42 },
    { x: 24, y: 42 },
    null,
    null,
    null,
    null,
    { x: 24, y: 43 },
    { x: 25, y: 43 },
    null,
    null,
    { x: 25, y: 42 },
  ],
};
/** Kleinster Seed 1 … 500 mit d(0, 2) = 37 (Felsbucht, AK-E4-03), und d(0, 1) dieses Seeds. */
export const SEED_D37 = 13;
export const D_HOME_A_AT_SEED_D37 = 29;
