import type { BuildingDef, BuildingDefId, Cost } from '../types';

const cost = (money: number, wood: number, tools: number, stone: number): Cost => ({
  money,
  wood,
  tools,
  stone,
});

export const BUILDING_DEFS: Record<BuildingDefId, BuildingDef> = {
  kontor: {
    id: 'kontor',
    name: 'Kontor',
    w: 2,
    h: 2,
    cost: cost(0, 0, 0, 0),
    upkeep: 0,
    category: 'infrastructure',
    supplyRadius: 8,
    site: [{ kind: 'coast' }],
  },
  market: {
    id: 'market',
    name: 'Marktplatz',
    w: 2,
    h: 2,
    cost: cost(200, 10, 3, 0),
    upkeep: 10,
    category: 'infrastructure',
    supplyRadius: 8,
    site: [],
  },
  house: {
    id: 'house',
    name: 'Wohnhaus',
    w: 1,
    h: 1,
    cost: cost(50, 3, 0, 0),
    upkeep: 0,
    category: 'housing',
    site: [{ kind: 'supply' }],
  },
  fisher: {
    id: 'fisher',
    name: 'Fischerhütte',
    w: 1,
    h: 1,
    cost: cost(100, 5, 2, 0),
    upkeep: 5,
    category: 'production',
    produces: 'food',
    cycle: 40,
    site: [{ kind: 'coast' }],
  },
  lumberjack: {
    id: 'lumberjack',
    name: 'Holzfäller',
    w: 1,
    h: 1,
    cost: cost(50, 0, 1, 0),
    upkeep: 5,
    category: 'production',
    produces: 'wood',
    cycle: 30,
    site: [{ kind: 'radius', terrain: 'forest', radius: 2, min: 1 }],
  },
  quarry: {
    id: 'quarry',
    name: 'Steinbruch',
    w: 1,
    h: 1,
    cost: cost(150, 10, 3, 0),
    upkeep: 10,
    category: 'production',
    produces: 'stone',
    cycle: 60,
    site: [{ kind: 'adjacent', terrain: 'mountain', min: 1 }],
  },
  sheepfarm: {
    id: 'sheepfarm',
    name: 'Schäferei',
    w: 2,
    h: 2,
    cost: cost(150, 10, 2, 0),
    upkeep: 10,
    category: 'production',
    produces: 'wool',
    cycle: 50,
    site: [{ kind: 'radius', terrain: 'grass', radius: 2, min: 4 }],
  },
  weaver: {
    id: 'weaver',
    name: 'Weberei',
    w: 2,
    h: 2,
    cost: cost(200, 15, 3, 0),
    upkeep: 15,
    category: 'production',
    produces: 'cloth',
    consumes: 'wool',
    cycle: 50,
    site: [],
  },
  canefarm: {
    id: 'canefarm',
    name: 'Zuckerrohrplantage',
    w: 2,
    h: 2,
    cost: cost(150, 10, 2, 0),
    upkeep: 10,
    category: 'production',
    produces: 'cane',
    cycle: 50,
    site: [{ kind: 'radius', terrain: 'grass', radius: 2, min: 4 }],
  },
  distillery: {
    id: 'distillery',
    name: 'Brennerei',
    w: 2,
    h: 2,
    cost: cost(250, 15, 4, 5),
    upkeep: 20,
    category: 'production',
    produces: 'rum',
    consumes: 'cane',
    cycle: 50,
    site: [],
  },
  chapel: {
    id: 'chapel',
    name: 'Kapelle',
    w: 2,
    h: 2,
    cost: cost(300, 20, 5, 10),
    upkeep: 15,
    category: 'public',
    service: 'faith',
    serviceRadius: 10,
    site: [],
  },
  school: {
    id: 'school',
    name: 'Schule',
    w: 2,
    h: 2,
    cost: cost(400, 25, 8, 15),
    upkeep: 25,
    category: 'public',
    service: 'school',
    serviceRadius: 10,
    site: [],
  },
};
export const BUILDING_IDS = Object.keys(BUILDING_DEFS) as BuildingDefId[];
export const ROAD_COST = 5;
