import type { BuildingDef, BuildingDefId, Cost } from '../types';

const cost = (money: number, wood: number, tools: number, stone: number): Cost => ({
  money,
  wood,
  tools,
  stone,
});

export const BUILDING_DEFS: Record<BuildingDefId, BuildingDef> = {
  kontor: {
    id: 'kontor',
    name: 'Kontor',
    w: 2,
    h: 2,
    cost: cost(0, 0, 0, 0),
    upkeep: 0,
    category: 'infrastructure',
    supplyRadius: 8,
    site: [{ kind: 'coast' }],
  },
  market: {
    id: 'market',
    name: 'Marktplatz',
    w: 2,
    h: 2,
    cost: cost(200, 10, 3, 0),
    upkeep: 10,
    category: 'infrastructure',
    supplyRadius: 8,
    site: [],
  },
  house: {
    id: 'house',
    name: 'Wohnhaus',
    w: 1,
    h: 1,
    cost: cost(50, 3, 0, 0),
    upkeep: 0,
    category: 'housing',
    site: [{ kind: 'supply' }],
  },
  fisher: {
    id: 'fisher',
    stormAffected: true,
    name: 'Fischerhütte',
    w: 1,
    h: 1,
    cost: cost(100, 5, 2, 0),
    upkeep: 5,
    category: 'production',
    flammable: true,
    produces: 'food',
    cycle: 40,
    site: [{ kind: 'coast' }],
  },
  hunter: {
    id: 'hunter',
    name: 'Jagdhütte',
    w: 1,
    h: 1,
    cost: cost(50, 2, 1, 0),
    upkeep: 5,
    category: 'production',
    flammable: true,
    produces: 'food',
    cycle: 50,
    site: [{ kind: 'radius', terrain: 'forest', radius: 3, min: 10, free: true }],
  },
  cattlefarm: {
    id: 'cattlefarm',
    name: 'Rinderfarm',
    w: 2,
    h: 2,
    cost: cost(250, 15, 3, 0),
    upkeep: 10,
    category: 'production',
    flammable: true,
    stormAffected: true,
    produces: 'food',
    cycle: 20,
    site: [{ kind: 'radius', terrain: 'grass', radius: 3, min: 16, free: true }],
  },
  lumberjack: {
    id: 'lumberjack',
    stormAffected: true,
    name: 'Holzfäller',
    w: 1,
    h: 1,
    cost: cost(50, 0, 1, 0),
    upkeep: 5,
    category: 'production',
    flammable: true,
    produces: 'wood',
    cycle: 30,
    site: [{ kind: 'radius', terrain: 'forest', radius: 2, min: 1, free: true }],
  },
  quarry: {
    id: 'quarry',
    name: 'Steinbruch',
    w: 1,
    h: 1,
    cost: cost(150, 10, 3, 0),
    upkeep: 10,
    category: 'production',
    flammable: true,
    produces: 'stone',
    cycle: 60,
    site: [{ kind: 'adjacent', terrain: 'mountain', min: 1 }],
  },
  sheepfarm: {
    id: 'sheepfarm',
    stormAffected: true,
    name: 'Schäferei',
    w: 2,
    h: 2,
    cost: cost(150, 10, 2, 0),
    upkeep: 10,
    category: 'production',
    flammable: true,
    produces: 'wool',
    cycle: 50,
    site: [{ kind: 'radius', terrain: 'grass', radius: 2, min: 4 }],
  },
  weaver: {
    id: 'weaver',
    name: 'Weberei',
    w: 2,
    h: 2,
    cost: cost(200, 15, 3, 0),
    upkeep: 15,
    category: 'production',
    flammable: true,
    produces: 'cloth',
    consumes: ['wool'],
    cycle: 50,
    site: [],
  },
  canefarm: {
    id: 'canefarm',
    stormAffected: true,
    name: 'Zuckerrohrplantage',
    w: 2,
    h: 2,
    cost: cost(150, 10, 2, 0),
    upkeep: 10,
    category: 'production',
    flammable: true,
    produces: 'cane',
    cycle: 50,
    site: [{ kind: 'radius', terrain: 'grass', radius: 2, min: 4 }],
  },
  distillery: {
    id: 'distillery',
    name: 'Brennerei',
    w: 2,
    h: 2,
    cost: cost(250, 15, 4, 5),
    upkeep: 20,
    category: 'production',
    flammable: true,
    produces: 'rum',
    consumes: ['cane'],
    cycle: 50,
    site: [],
  },
  toolmaker: {
    id: 'toolmaker',
    name: 'Werkzeugmacher',
    w: 2,
    h: 2,
    cost: cost(200, 15, 3, 0),
    upkeep: 25,
    category: 'production',
    flammable: true,
    produces: 'tools',
    consumes: ['wood'],
    cycle: 80,
    requiresService: 'school',
    site: [],
  },
  chapel: {
    id: 'chapel',
    name: 'Kapelle',
    w: 2,
    h: 2,
    cost: cost(300, 20, 5, 10),
    upkeep: 15,
    category: 'public',
    flammable: true,
    service: 'faith',
    serviceRadius: 10,
    site: [],
  },
  school: {
    id: 'school',
    name: 'Schule',
    w: 2,
    h: 2,
    cost: cost(400, 25, 8, 15),
    upkeep: 25,
    category: 'public',
    flammable: true,
    service: 'school',
    serviceRadius: 10,
    site: [],
  },
  firestation: {
    id: 'firestation',
    name: 'Feuerwache',
    w: 1,
    h: 1,
    cost: cost(150, 10, 2, 0),
    upkeep: 10,
    category: 'public',
    serviceRadius: 8,
    fireProtection: true,
    site: [],
  },
  bathhouse: {
    id: 'bathhouse',
    name: 'Badehaus',
    w: 2,
    h: 2,
    cost: cost(500, 30, 10, 20),
    upkeep: 30,
    category: 'public',
    flammable: true,
    service: 'bath',
    serviceRadius: 10,
    site: [],
  },
  glassworks: {
    id: 'glassworks',
    name: 'Glashütte',
    w: 2,
    h: 2,
    cost: cost(300, 20, 6, 10),
    upkeep: 25,
    category: 'production',
    flammable: true,
    produces: 'glass',
    consumes: ['stone', 'wood'],
    cycle: 50,
    site: [],
  },
  kontor2: {
    id: 'kontor2',
    name: 'Kontor',
    w: 2,
    h: 2,
    cost: cost(800, 20, 8, 10),
    upkeep: 10,
    category: 'infrastructure',
    supplyRadius: 8,
    site: [{ kind: 'coast' }, { kind: 'foreignNoKontor' }],
  },
  spicefarm: {
    id: 'spicefarm',
    stormAffected: true,
    name: 'Gewürzplantage',
    w: 2,
    h: 2,
    cost: cost(200, 12, 3, 0),
    upkeep: 15,
    category: 'production',
    flammable: true,
    produces: 'spice',
    cycle: 50,
    site: [
      { kind: 'radius', terrain: 'grass', radius: 2, min: 4 },
      { kind: 'islandTrait', trait: 'spice' },
    ],
  },
  townhall: {
    id: 'townhall',
    name: 'Amtsstube',
    w: 2,
    h: 2,
    cost: cost(200, 15, 2, 5),
    upkeep: 20,
    category: 'public',
    flammable: true,
    maxCount: { n: 1, reason: 'Es gibt schon eine Amtsstube' },
    site: [],
  },
};
export const BUILDING_IDS = Object.keys(BUILDING_DEFS) as BuildingDefId[];
export const ROAD_COST = 5;
export const ROAD_COST_OBJ: Cost = { money: ROAD_COST, wood: 0, tools: 0, stone: 0 };
/** Unterhalt eines stillgelegten Betriebs in Prozent (I-035, Spec §8 S4). */
export const PAUSED_UPKEEP_PCT = 50;
